version: "3.7"
services:
  ldap:
    build:
      context: ldap
      dockerfile: Dockerfile
    ports:
      - "10389:10389"
      - "10636:10636"
  database:
    build:
      context: postgres
      dockerfile: Dockerfile
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"