version: "3.7"
services:
  ldap:
    build:
      context: ldap
      dockerfile: Dockerfile
    ports:
      - "10389:10389"
      - "10636:10636"
  database:
    build:
      context: postgres
      dockerfile: Dockerfile
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  mq:
    build:
      context: message-broker
      dockerfile: Dockerfile
    ports:
      - "1414:1414"
  app:
    build:
      context: app
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - database
      - ldap
    ports:
      - "2005:2005"